version: "3.9"

services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: geoatlas_postgres
    environment:
      POSTGRES_USER: geoatlas
      POSTGRES_PASSWORD: geoatlas_dev
      POSTGRES_DB: geoatlas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoatlas"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: geoatlas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: geoatlas_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: geoatlas_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./ops/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

  grafana:
    image: grafana/grafana:11.2.0
    container_name: geoatlas_grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./ops/observability/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  postgres_data:
  redis_data:
  es_data:
  grafana_data:
