"""
Phase 4: XGBoost Prediction Engine
====================================
Trains the XGBoost classifier on the GeoAtlas dataset generated by geoatlasDatasetBuilder.
Enforces multi:softprob for probability tracking, class weighting for Neutral dominance,
and precise feature culling to prevent raw returns leakage.

Usage:
    python backend/scripts/train_xgboost.py --dataset backend/tmp/phase4/dataset.csv
"""

import argparse
import json
import logging
from pathlib import Path
import sys

import numpy as np
import pandas as pd
import xgboost as xgb
from joblib import dump
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score
from sklearn.preprocessing import LabelEncoder

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("XGB_Trainer")

BACKEND_ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    parser = argparse.ArgumentParser(description="GeoAtlas XGBoost Training Engine")
    parser.add_argument("--dataset", type=str, default=str(BACKEND_ROOT / "tmp" / "phase4" / "multi_asset_dataset.csv"))
    parser.add_argument("--metadata", type=str, default=str(BACKEND_ROOT / "tmp" / "phase4" / "assets" / "BTCUSDT" / "dataset_meta.json"))
    parser.add_argument("--output-model", type=str, default=str(BACKEND_ROOT / "tmp" / "phase4" / "models" / "xgboost_regime.joblib"))
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    metadata_path = Path(args.metadata)
    output_model = Path(args.output_model)

    if not dataset_path.exists():
        logger.error("Dataset not found at %s. Run dataset_builder.py first.", dataset_path)
        sys.exit(1)

    # ── 1. Load Data ──
    logger.info("Loading dataset from %s ...", dataset_path)
    df = pd.read_csv(dataset_path)
    
    with metadata_path.open("r", encoding="utf-8") as f:
        meta = json.load(f)

    # Convert date to datetime to perform strict chronological split
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").reset_index(drop=True)

    # ── 1.5. Edge Target Engineering ──
    # Direction > Magnitude for weak signals
    if "sentiment_momentum" in df.columns:
        df["sentiment_trend"] = np.sign(df["sentiment_momentum"])
    
    # Event intensity spike isolates structural macro breakout days
    df["event_spike"] = (
        df["event_count"] > df["event_count"].rolling(7).mean()
    ).astype(int)
    
    # Volatility Breakout expansion check
    if "volatility_7d" in df.columns:
        df["volatility_spike"] = (
            df["volatility_7d"] > df["volatility_7d"].rolling(14).mean()
        ).astype(int)

    # ── 2. Feature Selection (Reducing Noise Space) ──
    # Feature explosion diluted the alpha. We strictly restrict to the proven core edge factors.
    top_features = [
        "max_abs_goldstein",
        "max_sent_lag_1",
        "max_sent_lag_2",
        "sentiment_trend",
        "event_count",
        "event_spike",
        "sentiment_x_volatility",
        "event_x_return",
        "ma_14",
        "return_7d",
        "vol_rank",
    ]
    
    # Intentionally dropping symbol_* to temporarily force pure event learning
    valid_features = top_features
    
    # Filter only available ones (to prevent crashes on missing intermediate features)
    features = [c for c in valid_features if c in df.columns]
    logger.info("Selected %d automated features for training.", len(features))
    
    # ── 3. Chronological Split (80/20) ──
    split_idx = int(len(df) * 0.8)
    train_df = df.iloc[:split_idx]
    test_df = df.iloc[split_idx:]
    
    X_train = train_df[features]
    y_train_raw = train_df["target"]
    
    X_test = test_df[features]
    y_test_raw = test_df["target"]
    
    logger.info("Train set: %d rows (%s to %s)", len(X_train), train_df["date"].min().date(), train_df["date"].max().date())
    logger.info("Test set:  %d rows (%s to %s)", len(X_test), test_df["date"].min().date(), test_df["date"].max().date())

    # ── 4. Target Encoding (Binary) ──
    # 0 = No Move, 1 = Massive Volatility Breakout
    le = LabelEncoder()
    y_train = le.fit_transform(y_train_raw)
    y_test = le.transform(y_test_raw)

    # ── 5. Class Weights ──
    # Force extreme penalty against missing a major market crisis/breakout
    class_weights = {
        0: 1.0,
        1: 4.0
    }
    sample_weights = np.array([class_weights[y] for y in y_train])

    # ── 6. Model Definition & Training ──
    logger.info("Initializing XGBoost Classifier ...")
    model = xgb.XGBClassifier(
        objective="binary:logistic",
        n_estimators=100,
        max_depth=3,            # Shallow trees to prevent overfitting 700 rows
        learning_rate=0.05,
        colsample_bytree=0.8,
        subsample=0.8,
        max_delta_step=1,       # Helps with extreme imbalanced classes
        early_stopping_rounds=15, # Stop if test performance plateaus
        random_state=42,
        eval_metric="logloss",
    )

    logger.info("Fitting model with Eval Set tracking ...")
    model.fit(
        X_train, y_train,
        sample_weight=sample_weights,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        verbose=False  # Keep console clean, we rely on logs
    )
    
    logger.info("Best iteration: %d", model.best_iteration)

    # ── 7. Evaluation & Metrics ──
    probs = model.predict_proba(X_test)

    # ── SIGNAL FILTERING LAYER ──
    # Model detects ALL possible moves. System trades ONLY best moves.
    threshold = 0.60
    top_k = 60

    # Probability of Class 1 (Volatile Breakout)
    breakout_prob = probs[:, 1]
    filtered_preds = np.zeros(len(probs))

    # Step 1 & 2 & 3: Combine probability threshold with Top-K cap
    valid_indices = np.where(breakout_prob > threshold)[0]
    
    if len(valid_indices) > 0:
        # Sort valid indices by their probability (ascending)
        sorted_valid = valid_indices[np.argsort(breakout_prob[valid_indices])]
        # Take the top_k strongest
        top_indices = sorted_valid[-top_k:]
        filtered_preds[top_indices] = 1

    # Step 4: Regime Filter (Game Changer)
    # Only trade when event volume actually spikes heavily above background noise
    if "event_spike" in test_df.columns:
        event_spike = test_df["event_spike"].values
        filtered_preds[event_spike != 1] = 0

    # Convert back to original labels (0, 1) for report
    y_test_original = le.inverse_transform(y_test)
    preds_original = le.inverse_transform(filtered_preds.astype(int))

    print("\n" + "=" * 60)
    print("  XGBOOST CLASSIFICATION REPORT (TUNED THRESHOLDS)")
    print("=" * 60)
    print(classification_report(y_test_original, preds_original, zero_division=0))

    # ── TRADING SYSTEM METRICS ──
    signal_mask = (filtered_preds == 1)
    coverage = np.mean(signal_mask)
    
    print("  TRADING SYSTEM METRICS")
    print(f"  Coverage (Actionable Signals): {coverage:.1%}")

    if signal_mask.sum() > 0:
        non_neutral_acc = accuracy_score(y_test[signal_mask], filtered_preds[signal_mask])
        print(f"  Overall Breakout Precision:      {non_neutral_acc:.1%} ({signal_mask.sum()} total trades)")
    else:
        print("  Overall Breakout Precision:      N/A")

    # ── SIGNAL RANKING ──
    confidence = np.max(probs, axis=1)
    active_signals = np.where(signal_mask)[0]
    if len(active_signals) > 0:
        active_confs = confidence[active_signals]
        sorted_active = active_signals[np.argsort(active_confs)[::-1]]
        top_k = min(10, len(sorted_active))
        top_idx = sorted_active[:top_k]
        top_acc = np.mean(y_test[top_idx] == filtered_preds[top_idx])
        print(f"\n  Top {top_k} Strongest Signals Acc:  {top_acc:.1%}")

    print("\n  CONFUSION MATRIX")
    print("  " + str(le.classes_))
    print(confusion_matrix(y_test_original, preds_original))
    
    # ── 8. Feature Importance (THE TRUTH) ──
    importance = pd.Series(model.feature_importances_, index=X_train.columns)
    top_features = importance.sort_values(ascending=False).head(15)
    
    print("\n" + "=" * 60)
    print("  FEATURE IMPORTANCE LEADERBOARD")
    print("=" * 60)
    print(top_features)
    print("-" * 60)
    
    # Asserting Edge Signals
    target_signals = ["sentiment_lag_1", "sentiment_x_volatility", "event_x_return"]
    found_signals = [f for f in target_signals if f in top_features.index and top_features[f] > 0.01]
    if len(found_signals) < 1:
        logger.warning("The expected edge features (lags/interactions) are NOT dominating the model.")
        logger.warning("Most influential feature: %s", top_features.index[0])
    else:
        logger.info("Confirmed edge signals actively driving splits: %s", found_signals)

    # ── 9. Serialization ──
    output_model.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "model_type": "xgboost_regime_clf",
        "pipeline": model,
        "features": features,
        "label_encoder": le,
        "normalization_stats": meta.get("normalization_stats", {}),
    }
    
    dump(payload, output_model)
    logger.info("Model and pipeline exported to %s", output_model)

if __name__ == "__main__":
    main()
